services:
  - type: web
    name: streamlit-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: GROQ_API_KEY
        value: <set-in-render-dashboard>